'use strict';
const assert=require('node:assert/strict');
global.SnakeGame=require('./game.js').SnakeGame;
global.TetrisGame=require('./tetris.js').TetrisGame;
class E{constructor(dataset={}){this.dataset=dataset;this.listeners=new Map();this.attrs=new Map();this.classList={add(){},remove(){},toggle(){}};this.hidden=false;this.disabled=false;this.textContent='';this.focused=false;this.scrolled=false;}addEventListener(t,f){this.listeners.set(t,f)}setAttribute(k,v){this.attrs.set(k,v)}getAttribute(k){return this.attrs.get(k)||null}querySelector(){return label}focus(){this.focused=true}scrollIntoView(){this.scrolled=true}}
const ctx={fillRect(){},beginPath(){},arc(){},fill(){},strokeRect(){}};
const label=new E(),nav=new E(),toggle=new E();toggle.setAttribute('aria-expanded','false');
const panels=['home','profile','work','games','contact'].map(panel=>new E({panel}));
const panelLinks=['home','games'].map(panelLink=>new E({panelLink}));
const gameViews=['snake','tetris'].map(gameView=>new E({gameView}));
const openGames=['snake','tetris'].map(openGame=>new E({openGame}));
const backs=[new E(),new E()];
const snakeDirections=['up','left','down','right'].map(snakeDirection=>new E({snakeDirection}));
const tetrisActions=['left','rotate','right','down','drop'].map(tetrisAction=>new E({tetrisAction}));
const ids=['main-content','current-year','game-library','game-canvas','game-overlay','game-message','game-hint','game-status','score','best-score','start-game','pause-game','restart-game','tetris-canvas','tetris-overlay','tetris-message','tetris-hint','tetris-status','tetris-score','tetris-lines','tetris-best','tetris-start','tetris-pause','tetris-restart'];
const map=new Map(ids.map(id=>[`#${id}`,new E()]));map.set('#site-nav',nav);map.set('.nav-toggle',toggle);
for(const key of ['#game-canvas','#tetris-canvas']){const canvas=map.get(key);canvas.width=key.includes('tetris')?300:400;canvas.height=key.includes('tetris')?600:400;canvas.getContext=()=>ctx;}
global.document={listeners:new Map(),querySelector:s=>map.get(s),querySelectorAll:s=>({'[data-panel]':panels,'[data-panel-link]':panelLinks,'[data-game-view]':gameViews,'[data-open-game]':openGames,'[data-game-back]':backs,'[data-snake-direction]':snakeDirections,'[data-tetris-action]':tetrisActions}[s]||[]),addEventListener(t,f){this.listeners.set(t,f)}};
global.window={addEventListener(){}};global.innerWidth=1440;global.location={hash:''};global.history={pushState(_a,_b,hash){location.hash=hash}};global.localStorage={getItem(){return null},setItem(){}};
const frames=[];global.requestAnimationFrame=callback=>{frames.push(callback);return frames.length};
require('./script.js');
assert.equal(frames.length,1,'one shared animation frame must be scheduled');
assert.ok(map.get('#start-game').listeners.has('click'));assert.ok(map.get('#tetris-start').listeners.has('click'));
assert.ok(document.listeners.has('keydown'));assert.ok(map.get('#game-canvas').listeners.has('touchstart'));
assert.equal(openGames.every(element=>element.listeners.has('click')),true);
openGames[1].listeners.get('click')();
assert.equal(map.get('#tetris-canvas').focused,true,'Tetris canvas must receive focus when selected');
assert.equal(map.get('#tetris-canvas').scrolled,true,'Tetris canvas must scroll into view when selected');
frames.shift()(200);assert.equal(frames.length,1,'one successor frame must be scheduled');
console.log('browser runtime smoke: PASS');
